# Generated by Django 2.0.3 on 2018-03-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
